feat(jobs): add jobs for linkedlist rbegin/rend
yvizel/verify-c-common pull request #22
Opened 2020-10-06 19:34 UTC by danblitzhou

- added jobs for `aws_linked_list_rbegin` and  `aws_linked_list_rend`
- added `ensure_linked_list_is_allocated_nd` in helper library; this function is useful for verifying linked list functions that only concern the front item and the back item (other than head and tail).

2020-10-06 21:50 UTC, agurfinkel commented
close, but lots of redundancies that raises some questions. Let's clean it up before accepting.

2020-10-06 21:57 UTC, danblitzhou commented on seahorn/jobs/linked_list_rend/CMakeLists.txt
> +configure_file(sea.yaml sea.yaml @ONLY)
no job sea.yaml, will remove

2020-10-07 00:04 UTC, agurfinkel requested changes

2020-10-07 00:04 UTC, agurfinkel commented on seahorn/jobs/linked_list_rend/CMakeLists.txt
> +configure_file(sea.yaml sea.yaml @ONLY)
also max size

2020-10-07 00:44 UTC, danblitzhou commented on seahorn/jobs/linked_list_rbegin/aws_linked_list_rbegin_harness.c
> +    assume(aws_linked_list_is_valid(&list));
It is if we keep `AWS_DEEP_CHECKS=0`; this essentially checks `list && list->head.next && list->head.prev == NULL && list->tail.prev && list->tail.next == NULL`; I believe I can make this compatible with the additional length > 2 models by adding `assume(list->head.next)` and `assume(list->tail.prev)`

2020-10-07 00:45 UTC, danblitzhou commented on seahorn/lib/linked_list_helper.c
> +                                            size_t max_length, size_t *length) {
does `ensure_linked_list_is_initialized_nd` sound more reasonable?

2020-10-07 00:47 UTC, agurfinkel commented on seahorn/jobs/linked_list_rbegin/aws_linked_list_rbegin_harness.c
> +    assume(aws_linked_list_is_valid(&list));
maybe better to have our version to have full control of the pf

2020-10-07 00:50 UTC, agurfinkel commented on seahorn/lib/linked_list_helper.c
> +                                            size_t max_length, size_t *length) {
not really. 

there are 3 different functions like this that we seem to need. The names should reflect that. Check Sidharth PR that is still open. 

I think we are using linked_front for forward linked list, linked_back for back linked.

2020-10-07 04:08 UTC, danblitzhou commented
addressed review comments:
- broke `ensure_linked_list_is_allocated_nd` into three function for different use case (specifically for length > 2)
- enabled `sea_aws_linked_list_is_valid` to check linked list shallowly, behaviour can be switched using macro constant `SEA_DEEP_CHECKS` similar to `AWS_DEEP_CHECKS`
- other renaming and small tweaks

2020-10-07 04:09 UTC, danblitzhou commented on seahorn/jobs/linked_list_rend/CMakeLists.txt
> +  # We will use our own function for is_valid check hence AWS_DEEP_CHECK is off
promise is met!

2020-10-07 04:16 UTC, agurfinkel requested changes
almost there

2020-10-07 04:16 UTC, agurfinkel commented on seahorn/jobs/linked_list_rbegin/CMakeLists.txt
> +MATH(EXPR UNROLL_BOUND "${MAX_LINKED_LIST_ITEM_ALLOCATION_SIZE} + 2")
not needed

2020-10-07 04:16 UTC, agurfinkel commented on seahorn/jobs/linked_list_rbegin/aws_linked_list_rbegin_harness.c
> +    // if (length > 2) {
remove

2020-10-07 04:16 UTC, agurfinkel commented on seahorn/jobs/linked_list_rend/CMakeLists.txt
> +MATH(EXPR UNROLL_BOUND "${MAX_LINKED_LIST_ITEM_ALLOCATION_SIZE} + 2")
not needed

2020-10-07 04:39 UTC, danblitzhou commented
last review comments addressed

2020-10-07 11:41 UTC, agurfinkel approved these changes

2020-10-07 11:42 UTC, merged